#!groovy

/**
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright IBM Corporation 2020
 */

def PROJECT_ROOT_PATH = 'performance/server'

node('ibm-jenkins-slave-nvm') {
  def lib = library("jenkins-library").org.zowe.jenkins_shared_library

  def pipeline = lib.pipelines.nodejs.NodeJSPipeline.new(this)

  pipeline.admins.add("jackjia")

  pipeline.setup(
    packageName    : 'org.zowe.metrics-server',
    baseDirectory  : PROJECT_ROOT_PATH,
    nodeJsVersion  : 'v10.18.1',
    initWithColor  : true,
    auditWithColor : true,
    lintWithColor  : true
  )

  pipeline.build(displayAnsiColor: true)

  pipeline.test(
    name          : 'Unit',
    operation     : {
      echo "under construction"
    },
    allowMissingJunit : true,
    displayAnsiColor  : true
  )

  // we have pax packaging step
  pipeline.packaging(
    name             : 'zowe-metrics-server',
    displayTimestamp : true
  )

  // define we need publish stage
  pipeline.publish(
    operation: {
      echo "Default npm publish will be skipped."
    },
    artifacts: [
      ".pax/zowe-metrics-server.pax"
    ]
  )

  // define we need release stage
  pipeline.release()

  pipeline.end()
}
