{
 "title": "Zowe Metrics (SDSF vs RMF)",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Overall",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cpupr{source=\"rmf.dds\",item=\"\"}",
     "legendFormat": "CPU %"
    },
    {
     "expr": "auxpct{source=\"sdsf.sys\"}",
     "legendFormat": "Auxiliary %"
    },
    {
     "expr": "spoolpct{source=\"sdsf.sys\"}",
     "legendFormat": "Spool %"
    }
   ]
  },
  {
   "title": "Total Zowe CPU %",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum(cpupr{source=\"rmf.dds\",item=~\"ZWE.*\"})"
    }
   ]
  },
  {
   "title": "Central Storage %",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "csapct{source=\"sdsf.sys\"}",
     "legendFormat": "Common Storage Area (CSA) %"
    },
    {
     "expr": "sqapct{source=\"sdsf.sys\"}",
     "legendFormat": "System Queue Area (SQA) %"
    },
    {
     "expr": "ecsapct{source=\"sdsf.sys\"}",
     "legendFormat": "Extended Common Area (ECSA) %"
    },
    {
     "expr": "esqapct{source=\"sdsf.sys\"}",
     "legendFormat": "\tExtended System Queue Area (ESQA) %"
    }
   ]
  },
  {
   "title": "Real Storage (frames)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "real{source=\"sdsf.sys\"}"
    }
   ]
  },
  {
   "title": "Start IO Rate (EXCPs / sec)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "targets": [
    {
     "expr": "sio{source=\"sdsf.sys\"}"
    }
   ]
  },
  {
   "title": "Zowe CPU % (SDSF.DA)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpupr{source=\"sdsf.da\",process=~\"ZWE.+\"}",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Zowe CPU % (RMF)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpupr{source=\"rmf.dds\",item=~\"ZWE.*\"}",
     "legendFormat": "{{item}}"
    }
   ]
  },
  {
   "title": "Zowe CPU Time (SDSF.DA)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu{source=\"sdsf.da\",process=~\"ZWE.*\"}",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Zowe CPU Time (RMF)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu{source=\"rmf.dds\",item=~\"ZWE.*\"}",
     "legendFormat": "{{item}}"
    }
   ]
  },
  {
   "title": "Zowe CPU Time Delta (SDSD.DA)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(cpu{source=\"sdsf.da\",process=~\"ZWE.*\"}[30s])",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Zowe CPU Time Delta (RMF)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(cpu{source=\"rmf.dds\",item=~\"ZWE.*\"}[30s])",
     "legendFormat": "{{item}}"
    }
   ]
  },
  {
   "title": "Zowe Real Storage (SDSF.DA)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "real{source=\"sdsf.da\",process=~\"ZWE.*\"}",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Zowe Auxiliary Storage (RMF)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "real{source=\"rmf.dds\",item=~\"ZWE.*\"}",
     "legendFormat": "{{item}}"
    }
   ]
  },
  {
   "title": "z/OSMF -  CPU % (SDSF.DA)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpupr{source=\"sdsf.da\",process=~\"IZU.*\"}",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "z/OSMF -  CPU % (RMF)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpupr{source=\"rmf.dds\",item=~\"IZU.*\"}",
     "legendFormat": "{{item}}"
    }
   ]
  },
  {
   "title": "Overall CPU %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpupr{source=\"sdsf.sys\"}",
     "legendFormat": "SDSF.SYS"
    },
    {
     "expr": "cpupr{source=\"rmf.dds\",item=\"\"}",
     "legendFormat": "RMF"
    }
   ]
  },
  {
   "title": "CPU % (RMF)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpupr{source=\"rmf.dds\",item!=\"\"}",
     "legendFormat": "{{item}}"
    }
   ]
  }
 ]
}