{
 "title": "Zowe Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Overall CPU %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(CPUPR{process!=\"\"})"
    }
   ]
  },
  {
   "title": "Zowe CPU %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "sum(CPUPR{process=~\"ZWE.*\"})"
    }
   ]
  },
  {
   "title": "Start IO Rate (EXCPs / sec)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 13, "y": 0 },
   "targets": [
    { "expr": "SIO" }
   ]
  },
  {
   "title": "Real Storage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "REAL{process=\"\"}"
    }
   ]
  },
  {
   "title": "Zowe Address Spaces - CPU %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "CPUPR{process=~\"ZWE.+\"}",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Zowe Address Spaces - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "REAL{process=~\"ZWE.*\"}",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "z/OSMF -  CPU %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "CPUPR{process=~\"IZU.*\"}",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "z/OSMF - Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "REAL{process=~\"IZU.+\"}",
     "legendFormat": "{{process}}"
    }
   ]
  }
 ]
}