[#--
/*
* This program and the accompanying materials are made available under the terms of the *
* Eclipse Public License v2.0 which accompanies this distribution, and is available at *
* https://www.eclipse.org/legal/epl-v20.html                                      *
*                                                                                 *
* SPDX-License-Identifier: EPL-2.0                                                *
*                                                                                 *
* Copyright Contributors to the Zowe Project.                                     *
*                                                                                 *
*/
--]

[#--
    The AsciiDoc generated by this template produces a markdown file with the following:

    * A list of dependencies used by the component within Zowe, along with some basic information
        such as version, source repository link, and license.
--]

[#assign PurlUtils = statics['org.ossreviewtoolkit.model.utils.PurlUtilsKt']]
[#if projects?has_content]
| Third-party Software | Version | License | GitHub |
| -------------------- | --------| ------- | ------ |
[#list packages as package]
[#if !package.excluded]
[#--
 ## The below line will return package data and dump it to the output file. Useful for debugging. Used elsewhere.
${ortResult.getPackage(package.id)}
 --]
[#assign ortPkg = ortResult.getPackage(package.id)]

[#-- Package Homepage/Link --]
[#if ortPkg.metadata.homepageUrl?has_content]
    [#assign packageUrl = ortPkg.metadata.homepageUrl?replace("ssh://git@", "https://", "r")]
[#else]
    [#assign packageUrlRaw = ortPkg.metadata.vcsProcessed.url]
    [#assign packageUrl = packageUrlRaw?replace("ssh://git@", "https://", "r")]
[/#if]
[#-- Package Name --]
[#if package.id.namespace?has_content]
    [#assign packageName = package.id.namespace + '/' + package.id.name]
[#else]
    [#assign packageName = package.id.name]
[/#if]
[#-- Package License --]
[#if ortPkg.metadata.declaredLicenses?has_content]
    [#assign packageLicense = ortPkg.metadata.declaredLicenses[0]]
[#elseif package.license.licenseInfo.declaredLicenseInfo.licenses?has_content]
    [#assign packageLicense = package.license.licenseInfo.declaredLicenseInfo.licenses[0]]
[#else]
    [#assign packageLicense = "none"]
[/#if]
| ${packageName} | ${package.id.version} | ${packageLicense} | [${package.id.name}](${packageUrl}) | 
[/#if]
[/#list]
[/#if]